### ISSUE TITLE
Hi from ruralinnovation!

### ISSUE THREAD

**Issue by defuneste** [matthewjrogers/dform#1]
Hi @matthewjrogers, I work now for CORI/RISI and I am very  impress by your work! thanks so much for structuring/organizing some of the coding practices! If you have some time to share/discuss a bit your experience at CORI/RISI it will be super helpfull for me.

Would you  also mind if I PR a bit the README.md or should we prefer we work in the fork?

**Comment by matthewjrogers** [comment]
Hi there @defuneste -- absolutely, I'd be happy to connect! My email address is matthew.rogers09@gmail.com -- let's find half an hour to catch up at some point.

I'd be happy to have you open a pull request. Only thing worth noting is that my intention is to get this package to CRAN at some point, so I'd like the main `dform` to not be CORI/RISI specific.

**Comment by defuneste** [comment]
Awesome, will next week be good with you? 

Will be great to follow the CRAN idea!

**Comment by matthewjrogers** [comment]
You bet -- send me an email directly and we can coordinate.
